version: '2.1'
services:
    nginx:
        container_name: talal_nginx
        build: ./nginx
        working_dir: /app
        ports:
          - "8000:8000"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
          - php
        depends_on:
          - db

    php:
        container_name: talal_php
        build: ./php
        working_dir: /php
        volumes:
          - ./php:/app

    db:
      image: mariadb
      container_name: talal_db
      volumes:
        - ./app/storage/mysql:/var/lib/mysql
      ports:
        - "5306:3306"
      restart: always
      environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: talal_db_test
          MYSQL_PASSWORD: root
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
